## Regresión Logística
# Tablas de contingencia

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../datasets/gender-purchase/Gender Purchase.csv")

In [3]:
df.head()

Gender Purchase
0  Female      Yes
1  Female      Yes
2  Female       No
3    Male       No
4    Male      Yes

In [4]:
df.shape

(511, 2)

In [5]:
contingency_table = pd.crosstab(df["Gender"],df["Purchase"])

In [6]:
contingency_table 

Purchase   No  Yes
Gender            
Female    106  159
Male      125  121

In [7]:
contingency_table.sum(axis=1)

Gender
Female    265
Male      246
dtype: int64

In [8]:
contingency_table.sum(axis=0)

Purchase
No     231
Yes    280
dtype: int64

In [9]:
contingency_table.astype("float").div(contingency_table.sum(axis=1), axis=0)

Purchase       No      Yes
Gender                    
Female    0.40000  0.60000
Male      0.50813  0.49187

## Probabilidad condicional

* ¿Cuál es la probabilidad de que un cliente compre un producto si es hombre?
* ¿Cuál es la probabilidad de que sabiendo que un cliente compra un producto sea hombre?

In [11]:
from IPython.display import display, Math, Latex

In [18]:
display (Math(r'P(Purchase|Male) = \frac {Número\ total\ de\ compras\ hechas\ por\ hombres}{Número\ total\ de\ hombres} =  \frac {Compran \cap Hombre}{Hombre}' ))

<IPython.core.display.Math object>

In [20]:
P1 = 121/(121+125)
P1

0.491869918699187

In [24]:
display (Math(r'P(Male|Purchase) = \frac {Número\ total\ de\ compras\ hechas\ por\ hombres}{Número\ total\ de\ compras} =  \frac {Compran \cap Hombre}{Total\ de\ compras}' ))

<IPython.core.display.Math object>

In [25]:
P2 = 121 / (121+ 159)
P2

0.43214285714285716

In [30]:
display (Math(r'P(No\ Purchase|Male) = 1- P(Purchase|Male)'))
1-P1

<IPython.core.display.Math object>

0.5081300813008129

In [31]:
display (Math(r'P(Female | Compra) = 1- P(Male| Compra)'))
1-P2

<IPython.core.display.Math object>

0.5678571428571428

In [38]:
display (Math(r'P(Purchase|Male)' ))
print(121/(121+125))
display (Math(r'P(No\ Purchase|Male)' ))
print(1- 121/(121+125))
display (Math(r'P(Purchase|Female)' ))
print(159/(159+106))
display (Math(r'P(No\ Purchase|Female)' ))
print(1- 159/(159+106))

<IPython.core.display.Math object>

0.491869918699187


<IPython.core.display.Math object>

0.5081300813008129


<IPython.core.display.Math object>

0.6


<IPython.core.display.Math object>

0.4


## Ratio de probabilidades
Cociente entre los casos de éxito sobre los casos de fracaso del suceso en cada grupo

In [64]:
display (Math(r'P_m = probabilidad\ de\ compra\ dado\ hombre ' ))
display (Math(r'odds_{purchase| male} =  \frac{P_m}{1-P_m} = \frac{N_{p,m}}{N_{\bar p , m}} = \frac{hombres\ compran}{hombres\ no\ compran  }' ))
display (Math(r'odds_{purchase| male} \in [0,+\infty] ' ))
display (Math(r'P_f = probabilidad\ de\ compra\ dado\ mujer ' ))
display (Math(r'odds_{purchase| female} =  \frac{P_f}{1-P_f} = \frac{N_{p,f}}{N_{\bar p , f}} = \frac{mujeres\ compran}{mujeres\ no\ compran  }' ))
display (Math(r'odds_{purchase| female} \in [0,+\infty] ' ))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [47]:
Pm = 121/(121+125)
Pf = 159/(159+106)
Pm, Pf

(0.491869918699187, 0.6)

In [50]:
odds_m = Pm/(1-Pm)
odds_f = Pf/(1-Pf)
odds_m, odds_f

(0.9680000000000002, 1.4999999999999998)

In [51]:
121/125

0.968

In [52]:
159/106

1.5

* Si el ratio es superior a 1 es más probable el éxito que el fracaso (Probabilidad de éxito > Probabilidad de fracaso)
* Si el ratio es inferior a 1 es más probable el fracaso que el éxito (Probabilidad de fracaso > Probabilidad de éxito)


In [67]:
display (Math(r'odds_{ratio} = \frac{odds_{purchase| male}}{odds_{purchase| female}} ' ))

<IPython.core.display.Math object>

In [69]:
odds_r = odds_m/ odds_f
odds_r

0.6453333333333335

## Regresión Logística desde Regresión Lineal

In [75]:
display (Math(r' y = \alpha + \beta \cdot x'))
display (Math(r' (x,y) \in [-\infty, +\infty]'))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [79]:
display (Math(r'P = probabilidad\ de\ compra\ dado\ hombre \in [0,1]'))
display (Math(r'x = variable\ independiente' ))
display (Math(r' ln(\frac{P}{1-P}) =  \alpha + \beta \cdot x \in [-\infty, +\infty]'))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [80]:
display (Math(r' \frac{P}{1-P} = e^{ \alpha + \beta \cdot x}'))

<IPython.core.display.Math object>

In [86]:
display (Math(r' e^ { \alpha + \beta \cdot x} = P(1 + e^ {\alpha + \beta \cdot x })'))

<IPython.core.display.Math object>

In [95]:
display (Math(r' P = \frac{e^ {\alpha + \beta \cdot x}} {1 + e^ {\alpha + \beta \cdot x} }') )

<IPython.core.display.Math object>

In [96]:
display (Math(r' P = \frac{1} {1 + e^ {-\alpha - \beta \cdot x} }') )

<IPython.core.display.Math object>

In [97]:
display (Math(r' P = \frac{1} {1 + e^ {-(\alpha + \beta \cdot x)} }') )

<IPython.core.display.Math object>

In [106]:
display (Math(r' Si\ \alpha + \beta \cdot x \ es\ muy\ pequeño\ (negativo),\ entonces\ P\ tiende\ a\ 0' ) )
display (Math(r' Si\ \alpha + \beta \cdot x \ es\ muy\ grande\ (positivo),\ entonces\ P\ tiende\ a\ 1' ) )
display (Math(r' Si\ \alpha + \beta \cdot x = 0, \ entonces\ P=0.5' ) )

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

## Regresión Logística múltiple

In [108]:
display (Math(r' P = \frac{1} {1 + e^ {-(\alpha + \sum_{i=1}^{n}\beta_i \cdot x_i)} }') )

<IPython.core.display.Math object>

In [117]:
display (Math(r' \vec{\beta} = (\beta_1, \beta_2, \cdots, \beta_n)') )
display (Math(r' \vec{X} = (x_1, x_2, \cdots, x_n)') )
display (Math(r' P = \frac{1} {1 + e^ {-(\alpha + \vec{\beta} \cdot \vec{X})} }') )

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

## Implementación del método de máxima verosimilitud en regresión logística

## Definir la función de entorno L(b)

In [3]:
from IPython.display import display, Math, Latex

In [4]:
display (Math(r' L(\beta) = \prod_{i=0}^n P_i^{y_i}(1 - P_i)^{y_i} '))

<IPython.core.display.Math object>

In [27]:
display (Math(r' P_i = P(Y_i=1 | x_i) '))

<IPython.core.display.Math object>

In [145]:
def likelihood(y,pi):
    import numpy as np
    total_prod = 1
    for i in range(len(y)):
        t = pi[i]
        if y[i]==0:
            t = 1-pi[i]
        total_prod  = total_prod*t
    return total_prod
        
    

## Calcular las probabilidades de cada observación

In [11]:
display (Math(r' P_i = \frac{1} {1 + e^ {-( \sum_{j=0}^{n}\beta_j \cdot x_{ij})} }') )

<IPython.core.display.Math object>

In [146]:
def logitprobs(X,beta):
    import numpy as np
    n_rows = np.shape(X)[0]
    n_cols = np.shape(X)[1]
    pi =  [0 for i in range(n_rows)] # lista de 0's
    expon = [0 for i in range(n_rows)] # lista de 0's
    for i in range(n_rows):
        expon[i] = 0
        for j in range(n_cols):
            ex = X[i][j]*beta[j][0]
            expon[i] += ex
        with np.errstate(divide="ignore", invalid="ignore"):
            pi[i] = 1/(1+np.exp(-expon[i]))
    return pi
        

## Calcular la matriz diagonal W

In [15]:
display (Math(r'W = diag(P_i \cdot (1-P_i))_{i=1}^n '))

<IPython.core.display.Math object>

In [16]:
import numpy as np

In [17]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [147]:
def findW(pi):
    import numpy as np
    n = len(pi)
    W = np.zeros((n,n))
    for i in range(n):
        print (i)
        W[i][i] = pi[i]*(1-pi[i])
    return W

## Obtener la función logística

In [62]:
display (Math(r" x_{n+1} = x_n - \frac{f(x_n)}{f'(x_n)} "))
display (Math(r" f(X) = X(Y-P) "))
display (Math(r" f'(X) = XWX^T "))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [148]:
def logistics(X,Y, limit):
    import numpy as np
    from numpy import linalg
    n_rows = np.shape(X)[0]
    bias = np.ones((n_rows,1))
    X_new = np.append(bias, X, axis = 1)
    n_cols = np.shape(X_new)[1]
    beta = np.zeros((n_cols,1))
    root_dif = np.zeros((n_cols,1))
    iter_i = 10000
    while (iter_i>limit):
        print("iter_ i =", iter_i)
        print("ilimit =", limit)
        print("X_new =", X_new)
        print("beta =", beta)
        pi = logitprobs(X_new,beta)
        print("pi= ", pi)
        W = findW(pi)
        print("W= ", W)
        print("X_new= ", X_new)
        print("X_new T= ", np.transpose(np.matrix(X_new)))
        print("Y - P = ", np.transpose(np.matrix(Y-np.transpose(pi))))
        num = np.transpose(np.matrix(X_new))*np.transpose(np.matrix(Y-np.transpose(pi))) #XT(Y-P)
        den = -np.matrix(np.transpose(X_new))*np.matrix(W)*np.matrix(X_new)
        inc = np.array(linalg.inv(den)*num)
        beta = beta - inc
        print("inc = ", inc)
        print("beta = ", beta)
        iter_i = np.sum(inc*inc)
        print(" iter_i = ", iter_i)
        Li = likelihood(Y,pi)
        print("Li = ", Li)
    return beta
        
        
    
    
    

## Comprobación experimental

In [105]:
import numpy as np

In [94]:
X = np.array(range(10)).reshape(10,1)

In [95]:
X.shape

(10, 1)

In [96]:
X

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [126]:
Y = [0, 0, 0, 0, 1, 0 ,1,0, 1,1]

In [127]:
Y

[0, 0, 0, 0, 1, 0, 1, 0, 1, 1]

In [98]:
bias = np.ones((10,1))

In [99]:
bias

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [100]:
X_new = np.append(bias, X, axis = 1)
X_new

array([[1., 0.],
       [1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.],
       [1., 5.],
       [1., 6.],
       [1., 7.],
       [1., 8.],
       [1., 9.]])

In [149]:
a = logistics(X,Y,0.00001)

iter_ i = 10000
ilimit = 1e-05
X_new = [[1. 0.]
 [1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]
 [1. 7.]
 [1. 8.]
 [1. 9.]]
beta = [[0.]
 [0.]]
pi=  [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
0
1
2
3
4
5
6
7
8
9
W=  [[0.25 0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.25 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.25 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.25 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.25 0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.25 0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.25 0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.25 0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.25 0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.25]]
X_new=  [[1. 0.]
 [1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]
 [1. 7.]
 [1. 8.]
 [1. 9.]]
X_new T=  [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]
Y - P =  [[-0.5]
 [-0.5]
 [-0.5]
 [-0.5]
 [ 0.5]
 [-0.5]
 [ 0.5

In [81]:
np.zeros(4)

array([0., 0., 0., 0.])

Y = -3.69557172 + 0.66220827* X En el modelo logístico P = 1/(1+ exp(-Y))

## Con el paquete stats de Python

In [153]:
import statsmodels.api as sm

In [154]:
Y

[0, 0, 0, 0, 1, 0, 1, 0, 1, 1]

In [155]:
X_new

array([[1., 0.],
       [1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.],
       [1., 5.],
       [1., 6.],
       [1., 7.],
       [1., 8.],
       [1., 9.]])

In [156]:
logit_model = sm.Logit(Y,X_new)

In [157]:
result = logit_model.fit()

Optimization terminated successfully.
         Current function value: 0.431012
         Iterations 6


In [158]:
print(result.summary())

                           Logit Regression Results                           
Dep. Variable:                      y   No. Observations:                   10
Model:                          Logit   Df Residuals:                        8
Method:                           MLE   Df Model:                            1
Date:                Mon, 23 Sep 2024   Pseudo R-squ.:                  0.3596
Time:                        14:14:41   Log-Likelihood:                -4.3101
converged:                       True   LL-Null:                       -6.7301
Covariance Type:            nonrobust   LLR p-value:                   0.02781
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -3.6956      2.289     -1.615      0.106      -8.182       0.791
x1             0.6622      0.400      1.655      0.098      -0.122       1.446
